# Generated by Django 5.2 on 2025-05-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='notes',
            new_name='background',
        ),
        migrations.AddField(
            model_name='birthday',
            name='relationship',
            field=models.CharField(default='Father', max_length=100),
            preserve_default=False,
        ),
    ]
