# Generated by Django 5.2 on 2025-05-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_rename_notes_birthday_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='birthday',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
